export const metadata = {
  title: 'Welcome to Next.js!',
  description: 'Generated by Md. Alamin',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
